#BLOBS
config:
  target: http://135.236.236.241
  plugins:
    metrics-by-endpoint: { } # Used to get metrics for each endpoint individually.
  phases:
    - name: "Main test"    # MAIN TESTS: duration: 30s, with 1 new clients/sec
      duration: 30
      arrivalRate: 5
  payload:
    path: ./data/updated_users.csv
    #loadAll: true # load the whole CSV
    order: sequence # selects users sequentially, default is random
    skipHeader: true # The first line is a header, so we want to skip it
    delimiter: "," # standard delimiter
    skipEmptyLines: true # not important in our case
    fields:
      - "userId"
      - "pwd"
      - "email"
      - "displayName"
scenarios:
  - name: 'Blobs'
    weight: 1
    flow:
      # Create users' shorts
      - post:
          url: "http://135.236.194.252/tukano/tukano-1/rest/shorts/{{ userId }}?pwd={{ pwd }}"
          headers:
            Content-Type: application/json
            Accept: application/json
          capture:
            - json: "$.id"
              as: "id"
      # Login users
      - post:
          url: "http://135.236.236.241/blobs-1/rest/login/{{ userId }}?pwd={{ pwd }}"
      # Create shorts' blobs
      - post:
          url: "http://135.236.236.241/blobs-1/rest/blobs/{{ id }}?token=token"
          headers:
            Content-Type: application/octet-stream
            body: \x00\x01\x02
      # Login users
      - post:
          url: "http://135.236.236.241/blobs-1/rest/login/{{ userId }}?pwd={{ pwd }}"
      # Download blobs
      - get:
          url: "http://135.236.236.241/blobs-1/rest/blobs/{{ id }}?token=token"
      # Login admin
      - post:
          url: "http://135.236.236.241/blobs-1/rest/login/admin?pwd=pwd"
      # Delete all blobs
      - delete:
          url: "http://135.236.236.241/blobs-1/rest/blobs/{{ userId }}?token=token"